### ISSUE TITLE
Can't access when running in docker 

### ISSUE THREAD

**Issue by ranying666** [edp963/davinci#1349]
I made a dockerfile to run davinci-0.3 .  

```
server:
  protocol: http
  address: 127.0.0.1
  port: 8080

  servlet:
    context-path: /

  # Userd for mail and download services, can be empty, careful configuration
  # By default, 'server.address' and 'server.port' is used as the string value.
  access: 
    address: 10.26.169.58
    port: 8686

```
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                               NAMES
17d4fe6dee21        353967c102a1        "./entrypoint.sh ./s…"   14 minutes ago      Up 14 minutes       0.0.0.0:8686->8080/tcp 
```

It's worked ok in docker CONTAINER.
```
root@17d4fe6dee21:/opt/davinci/bin# wget 127.0.0.1:8080
--2019-11-29 03:25:58--  http://127.0.0.1:8080/
Connecting to 127.0.0.1:8080... connected.
HTTP request sent, awaiting response... 200 
Length: unspecified [text/html]
Saving to: 'index.html'

index.html                               [ <=>                                                                   ]   2.56K  --.-KB/s    in 0s  
```

**But can not access from outsite!!**

```
wget 10.26.169.58:8686
--2019-11-29 11:29:18--  http://10.26.169.58:8686/
Connecting to 10.26.169.58:8686... failed: Connection refused.

```

**Could you help me ? how to config？**  

Thank you !
