### ISSUE TITLE
 java.lang.ClassNotFoundException: mongodb.jdbc.MongoDriver

### ISSUE THREAD

**Issue by FlyLesss** [edp963/davinci#1793]
添加了 3.6.3 的mongodriver  ，报错

**Comment by chenarmy** [comment]
me,too

**Comment by JavaLover4Ricky** [comment]
you can use unityjdbc instead of that

**Comment by JavaLover4Ricky** [comment]
> using 3.6.3 version mongodriver

you can use unityjdbc instead of that, the url is  https://www.unityjdbc.com/

**Comment by chenarmy** [comment]
> > using 3.6.3 version mongodriver
> 
> you can use unityjdbc instead of that, the url is https://www.unityjdbc.com/


datasource_driver.yml

```
mongo:
    name: mongo
    desc: mongodb
    version: 
    driver: mongodb.jdbc.MongoDriver
    keyword_prefix: \`
    keyword_suffix: \`
    alias_prefix: \"
    alias_suffix: \"
```

![image](https://user-images.githubusercontent.com/6418143/84251952-a0aa6680-ab40-11ea-857d-6d713e0fb22d.png)
