### ISSUE TITLE
server.servlet.context-path not working,404 not found

### ISSUE THREAD

**Issue by itbean-git** [edp963/davinci#2204]
In my application.yml
```
server:
  protocal: http
  address: 0.0.0.0
  port: 8080

  servlet:
    context-path: /davinci
```
but server.servlet.context-path params not working, debug in Chorme, request uri  not use  davinci as prefix.Please see the following screenshot.
![image](https://user-images.githubusercontent.com/71507243/119589022-95f5e980-be04-11eb-9dd1-82151c279e61.png)
