### ISSUE TITLE
发送截图一直卡在wait.until(ExpectedConditions.or(ConditionOfSign, ConditionOfWidth, ConditionOfHeight))

### ISSUE THREAD

**Issue by PhaerisWakfu** [edp963/davinci#2222]
excel可以正常发送，截图debug时一直卡在wait.until(ExpectedConditions.or(ConditionOfSign, ConditionOfWidth, ConditionOfHeight))
CHROME与驱动版本均为90
`Starting ChromeDriver 90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}) on port 41581
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1625629241.983][WARNING]: This version of ChromeDriver has not been tested with Chrome version 91.`
```yaml
screenshot:
  default_browser: CHROME
  timeout_second: 600
  phantomjs_path:
  chromedriver_path: D:\soft\chrome driver\chromedriver.exe
  remote_webdriver_url:
```
