### ISSUE TITLE
agg(column) as agg(metrics) 这样的处理在 PostgreSQL 数据库中报错

### ISSUE THREAD

**Issue by qiulin** [edp963/davinci#688]
如题目描述，在 PostgreSQL 数据库中会报如下错误：

[42601] ERROR: syntax error at or near "("

建议改成 `agg(column) as agg__metrics`这样的处理方式

**Comment by AndyFong** [comment]
可通过在 `datasource_driver.yml` 文件中，将 pgsql 配置部分中的 prefix 和 suffix 修改为双引号解决，如下：
```yaml
   keyword_prefix:\"
   keyword_suffix:\"
   alias_prefix: \"
   alias_suffix: \"
```
